language: ruby

rvm:
 - 1.9.2
 - 1.9.3
 - ree

bundler_args: --without development

before_script:
  - psql -c 'create database tweettriggers_test;' -U postgres
  - bundle exec rake dev:bootstrap
  - bundle exec rake db:migrate

script:
  - ./bin/test
