development:
  adapter: postgresql
  encoding: unicode
  database: tweettriggers_development
  pool: 5
  username: rails
  password: r4i75lol
  template: template0
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: tweettriggers_test
  pool: 5
  username: rails
  password: r4i75lol
  template: template0
  host: localhost
