development:
  adapter: postgresql
  encoding: unicode
  database: tweettriggers_development
  pool: 5
  username: rails
  password:
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: tweettriggers_test
  username: postgres
