
development:
  adapter: postgresql
  encoding: unicode
  database: twittertrigger_development
  pool: 5
  username: rails
  password:
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: twittertrigger_test
  pool: 5
  username: rails
  password:
  template: template0
